// <auto-generated />
namespace FoosballGames.Migrations

open System
open FoosballGames
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata

[<DbContext(typeof<FoosballGamesContext>)>]
type FoosballGamesContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasDefaultSchema("FoosballGames")
            .HasAnnotation("ProductVersion", "6.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63) |> ignore

        modelBuilder.Entity("FoosballGames.DbFoosballGame", (fun b ->

            b.Property<Guid>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                |> ignore

            b.Property<string>("JsonContent")
                .IsRequired(true)
                .HasColumnType("json")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("FoosballGames", "FoosballGames") |> ignore

        )) |> ignore

